version: "3.2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb123
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    environment:
      - REDIS_PASSWORD=redis123
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
